### ISSUE TITLE
hotel template has issue in https 

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#41]
https://www.206tours.com/info/holyland/hotels/david-citadel

**Comment by Andrey1901** [comment]
Hi @ronen206tours it was solved in #9

**Comment by ronen206tours** [comment]
i still have an issue with this page

![image](https://user-images.githubusercontent.com/38356174/50354262-ed4b4d80-0518-11e9-9a8a-08063c2f20e3.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, I've fixed it

**Comment by ronen206tours** [comment]
TY
